### ISSUE TITLE
Package not found in pip repository

### ISSUE THREAD

**Issue by AlexisTonneau** [XelK/pihole_api#3]
![image](https://user-images.githubusercontent.com/45481870/145101242-82b3e692-63b8-448d-acdc-b0c1fb8a9ff7.png)

**Comment by XelK** [comment]
Could you try to install this package again with `pip install pi-hole-api`. 
I updated the package so it has to support more python versions from 3.6 to 3.10.
If you still have problems check that the python version is >= 3.6.
